### PR TITLE
Add enable_tpm to toggle virtual TPM

### LINKED ISSUE #42: Support Setting TPM (Trusted Platform Module) - Needed to Support Windows 11 (RTM) VMs
#### Description

Now that Windows 11 has RTM'd, the requirement in Hyper-V is to have TPM (Trusted Platform Module) enabled. Otherwise you get an error immediately in the installer saying "This PC doesn't meet the minimum system requirements...". 

There is a simple checkbox in the settings if you are configuring it manually. We need a way to enable this from the packer plugin.

#### Use Case(s)

Attempting to use Packer to bootstrap a Windows 11 (RTM or later) VM.

#### Potential configuration

```
```

#### Potential References
One of many blog posts discussing the settings needed with screenshots - https://pureinfotech.com/enable-tpm-secure-boot-hyperv-install-windows-11/

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### PR DESCRIPTION
**Pull request by camjjack**
Introduce `enable_tpm` config which will turn on the virtual TPM for VM is set to `true`. Closes #42

### CODE REVIEW

**Comment by hathawcs** [comment]
Any chance this can be reviewed?

**Comment by ibeerens** [comment]
Is it possible to review the enable\_tpm option?

**Comment by brady-microsoft** [comment]
Hey there Hashicorp - 

The lack of this feature is a blocker to anyone wishing to use Packer for building Windows 11 images. [Windows 11 has TPM requirements](https://www.microsoft.com/en-us/windows/windows-11-specifications) that would be settled in Hyper-V through this feature. 

Is there anything I can do to help here?

**Comment by simonlock** [comment]
Hi,  Is it still not possible to build Win11 using Packer on HyperV?

**Comment by brady-microsoft** [comment]
Fantastic news. Thank you so much @nywilken !!

**Comment by ibeerens** [comment]
Great news!

**Comment by camjjack** [comment]
Thanks @nywilken

**Pull request merged**
